# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll Advanced Search
description: >- # this means to ignore newlines until "baseurl:"
  This will create a jekyll advanced search interface.
baseurl: "/jekyll-advancedsearch" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: niqui_o
github_username:  dnoneill

# Build settings
markdown: kramdown
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-feed
  - jekyll-lunr-advanced-js-search

view_facets: 5

  
lunr_settings: {"collections": ["people"],
  "fields": [
        {"searchfield": "id", "boost": 1, "jekyllfields": ["slug"]},
        {"searchfield": "ethnicity", "boost": 10, "jekyllfields": ["ethnicity"], "facetfield": true},
        {"searchfield": "name", "boost": 10, "jekyllfields": ["preferredName", "variantNames"]},
        {"searchfield": "occupation", "boost": 10, "jekyllfields": ["occupation"], "facetfield": true},
        {"searchfield": "description", "boost": 1, "jekyllfields": ["content"]},
        {"searchfield": "contributor", "boost": 1, "jekyllfields": ["contributions"], "widget": "flatten"},
        {"searchfield": "cities", "boost": 10, "parentfield": "workLocations", "jekyllfields": ["wlCity"], "widget": "nested", "facetfield": true},
        {"searchfield": "countries", "boost": 10, "parentfield": "workLocations", "jekyllfields": ["wlCountry"], "widget": "nested", "facetfield": true},
        {"searchfield": "works", "boost": 10, "widget": "relational", "collection": "works", "jekyllfields": ["preferredName", "variantName"], "matchfield" : "contributor", "secondaryfield": "contributorId"}
    ],
  "headerfield": "preferredName",
  "displayfields": [
    {"field" : "variantNames", "label": "Variant Name"}, 
    {"field": "occupation", "label":"Occupation", "joiner": "<br>", "truncate": 2},
    {"field": "born", "label":"Birth Year"},
    {"field": "works", "label":"Work", "joiner": "; ", "conditional": "true"}
  ],
    "atozsortfield" : 'preferredName',
    "fuzzysearchfields": ["name", "birthplace", "residences", "worklocations", "description"]

}

collections:
    people:
        output: true
        permalink: /people/:path
    works:
        output: true
        permalink: /works/:path
    docs:
      output: true
      permalink: /:path

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: people
  - scope:
      path: ""
      type: "works"
    values:
      layout: works


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
